### PR TITLE
implement reading from loggregator v2 api

### PR DESCRIPTION
**Pull request by johncornish**
This requires the RLP gateway to be deployed, which has been included in cf-deployment 4.5 (https://github.com/cloudfoundry/cf-deployment/releases/tag/v4.5.0)

Signed-off-by: John Cornish <jcornish@pivotal.io>

### CODE REVIEW

**Comment by frodenas** [comment]
@johncornish You're disabling the loggegrator v1 api, and I believe v2 (through LRP) was not introduced until PAS 2.4. Not all users have updated to the latest PAS version, so I'd like to keep v1 for a while. Can you please update the PR to enable v2 via a flag and keep the v1 logic?

**Comment by jtuchscherer** [comment]
@frodenas we made it optional to use the old firehose endpoint. The user now has to provide a `logging.url` which should be either a valid doppler URL or a valid log-stream URL. The user can also optionally specify the `logging.use-legacy-firehose` flag. This flag will tell the firehose-exporter whether the logging.url is meant to be a firehose endpoint or a log-stream endpoint.

**Comment by frodenas** [comment]
Thanks @johncornish and @jtuchscherer!

**Comment by jtuchscherer** [comment]
Thanks for merging this in.

**Pull request merged**
